### ISSUE TITLE
Timestamp displays as None from WA guano data in .wav (guano_dump.py)

### ISSUE THREAD

**Issue by parsingphase** [riggsd/guano-py#17]
Timestamp from Wildlife Acoustics Echo Meter Touch 2 (iPhone app) is shown as None in guano_dump output:

    (venv) root@be7e71f34666:/var/www/webroot/media/sessions/Session 20190430_210036# guano_dump.py PIPPYG_20190430_210244.wav | grep Timestamp
    Timestamp: None
    (venv) root@be7e71f34666:/var/www/webroot/media/sessions/Session 20190430_210036# tail -c800 PIPPYG_20190430_210244.wav
    [BINARY STRIPPED]guan/GUANO|Version: 1.0
    Firmware Version: App 2.7.7
    Length: 15.00
    Loc Position: 51.41691 -0.0671
    Loc Elevation: 55.62311
    Make: Wildlife Acoustics
    Model: Echo Meter Touch 2
    Original Filename: 20190430_210244.wav
    Samplerate: 256000
    Serial: E2B02356
    Species Auto ID: PIPPYG
    Species Manual ID:
    Timestamp: 2019-04-30 21:02:44+0100
    Note:
    WA|Echo Meter|Auto ID: PIPPYG
    WA|Song Meter|Audio settings: [{"prefix":"Yamato","trig max len":"15.00","rate":"256000","trig window":"3.00","trig min freq":"30000.00","trig level":"2.00","trig max freq":"128000.00","gain":"0.00"}]wamd�Echo Meter Touch E2B02356     App 2.7.72019-04-30 21:02:44+0100WGS84,51.41691,-0.0671,55.62311

Version info from Pipfile.lock:

        "guano": {
            "hashes": [
                "sha256:a913804a1844866d74eab3b38ec5b7d7759d8ad6238e6d90b88bfa4fd4e4b235",
                "sha256:fff5b8a63e713d47c0d8bb438bee989f2afb15c2a5aa95abd6e664f64786279d"
            ],
            "index": "pypi",
            "version": "==1.0.12"
        },

I note while processing this timestamp programatically in GuanoFile(filepath).item() that it *is* read from the guano data, but appears to have no timezone set, which causes a crash if you them call datetime.isoformat() on it. I would guess that parsing of this field is not setting a valid tz.

Happy to provide the wav file for testing; can also look at patching this myself at a later date once I'm more familiar with the library

**Comment by riggsd** [comment]
Could you please attach the actual WAV file? Thanks for the detailed
report!

**Comment by parsingphase** [comment]
Uploaded to https://www.dropbox.com/s/s4mxxpjj6b8dnq8/PIPPYG_20190430_210244.wav?dl=0 as I can't see how to attach a file to the ticket

**Comment by parsingphase** [comment]
Just noticed this:

    print(guano_file['Timestamp'].tzinfo)
    UTC100

**Comment by riggsd** [comment]
This file's timestamp - specifically its UTC offset - does not match the format as defined in the [GUANO 1.0 Specification](https://github.com/riggsd/guano-spec/blob/master/guano_specification.md#definitions-and-common-data-conventions).

<img width="773" alt="Screen Shot 2019-06-01 at 12 47 29 PM" src="https://user-images.githubusercontent.com/647785/58751469-dbc58480-846c-11e9-8a16-f339111434c8.png">

The GUANO specification says:

> Dates, times, and datetimes must appear in one of the following formats, which are subsets of the ISO 8601 and RFC 3339 specifications. ...
> 
> UTC Relative DateTime
> 
> 2015-12-31T23:59:59+04:00
> 2015-12-31T23:59:59.123+04:00
> 2015-12-31T23:59:59.123456+04:00

Note that UTC offsets are specified with a **colon** separating HH:MM. The timestamp as embedded in your .WAV file is, `2019-04-30 21:02:44+0100`; its UTC offset is missing the colon separator.

To be fair, both variations are supported by the sprawling [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) standard, but the GUANO Specification clearly states that timestamp must be one of the subsets explicitly noted in the Specification. [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) recommends exclusively the GUANO version.

**EDIT:** This .WAV file's timestamp is also missing the literal `T` character separating date from time, which - although it isn't specifically mentioned in the GUANO Specification - `guano-py` already supports since it's a "no brainer" conversion and (in my opinion) more legible than with a `T`. 


It would be easy to add support for this additional timestamp format to the `guano-py` library, but the question is whether that would be harmful to the community or not. The correct fix is for Wildlife Acoustics to add a colon to their UTC offset. If we silently support the alternate format in `guano-py`, then other GUANO implementations will eventually encounter the same problem.

**Comment by parsingphase** [comment]
If I'm reading the spec correctly they'd need to replace the space with a T, as well? (EDIT - ok, you beat me to that one)

I can always try to raise a bug report with Wildlife Acoustics to get this fixed - I agree with your logic on the risks of off-standard parsing. Is there space for a 'lenient date parsing' option that emphasises the presence of an issue? I note that there's already a concept of 'Strict mode' in https://guano-py.readthedocs.io/en/latest/api.html though I'm not sure it can be triggered by library users.

As an aside, what hex dumper is that? Looks useful!

**Comment by riggsd** [comment]
Let me investigate a bit further before contacting Wildlife Acoustics. This timestamp value passes our unit test suite, which is surprising(!) and doesn't explain why we're ending up with a `None` value.

The above screenshot is of [Hex Fiend](https://ridiculousfish.com/hexfiend/), an excellent hex editor for Macs.

**Comment by riggsd** [comment]
I added a `--strict` commandline option to `bin/guano_dump.py` which enables strict parsing mode. This file fails with the error:

```
Traceback (most recent call last):
  File "./bin/guano_dump.py", line 50, in <module>
    dump(fname, strict=strict)
  File "./bin/guano_dump.py", line 23, in dump
    print(gfile.to_string())
  File "/Users/driggs/workspace/guano-py/guano.py", line 406, in to_string
    v = self._serialize(k, v)
  File "/Users/driggs/workspace/guano-py/guano.py", line 220, in _serialize
    return serialize(value)
  File "/Users/driggs/workspace/guano-py/guano.py", line 170, in <lambda>
    'Timestamp': lambda value: value.isoformat() if value else '',
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

The problem is indeed the UTC offset, which our current code parses as having an offset of "positive 100 hours" (which the datetime API tries to interpret as 24 hours), when the intent is "positive 1 hours".

Again, this is an easy fix, but the question is whether we _should_ support it or not. I suppose a compromise is that it should fail in strict mode but "just work" in production mode, and we should request that Wildlife Acoustics update their UTC offset format for compliance with the GUANO Specification.

**Comment by parsingphase** [comment]
I think your compromise makes sense. Do you want to raise this with Wildlife Acoustics or should I? I'm figuring they may already know you as editor of the library (and Guano spec?).

As a thought, if you'd prefer to avoid the risks in allowing invalid data to pass silently, it might be worth changing the default on `guano_dump.py` to strict (ie, make the flag `--no-strict`), and also raising a warning if it's encountered in code using the GuanoFile class.

**Comment by riggsd** [comment]
I'll contact Wildlife Acoustics to ask for their input on this issue.

I've updated master branch to support this format for now, but will probably make it a strict/non-strict option before releasing version 1.0.13.

**Comment by parsingphase** [comment]
Excellent, many thanks for the incredibly quick & helpful response, too.

**Comment by parsingphase** [comment]
Hi David - I don't know if you've reached a decision on releasing a new version, but you might be interested in what I'm using your library for - see https://github.com/parsingphase/batbox

**Comment by parsingphase** [comment]
Hi David - 
 I notice a similar problem with parsing of WAMD data from WA's own files such as https://www.dropbox.com/s/j6gbxiqw6ds3iak/MYODAU_20180805_212228.wav?dl=0 - these also use +0100 format - so your new release should help fix this.

<img width="835" alt="WAMDtime" src="https://user-images.githubusercontent.com/867994/59979205-6583f000-95dc-11e9-8337-3baeecb44cde.png">

However - there's one further bug in `guano.tzoffset` at https://github.com/riggsd/guano-py/blob/master/guano.py#L66 - when you split the offset into hours and minutes, you're only applying the sign to the hours part, so (eg) a Newfoundland NST offset of -02:30 will calculate as `-2 + (30/60) = -1.5`, rather than `-2 + (-30/60) = -2.5` (https://www.timeanddate.com/time/time-zones-interesting.html)

**Comment by BCTSoundAnal** [comment]
I have just come across this issue.  Has WA been contacted and what is the outcome?

**Comment by riggsd** [comment]
I did not contact Wildlife Acoustics about this issue, which already exists in the wild, and must therefore be supported by production software even if it violates the specification.

The `master` branch correctly parses EMTouch2 timestamps, but have not done a final release yet.

**Comment by BCTSoundAnal** [comment]
Yep - pretty much the conclusion I had come to:-)

Thanks for your prompt response:-)

**Comment by riggsd** [comment]
@parsingphase I added a test for Newfoundland NST's `-02:30` tzoffset and fixed the bug, thank you!

`guano-py` 1.0.13 has officially been released, including all the fixes from this thread.

**Comment by parsingphase** [comment]
Excellent, thanks @riggsd
